// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Experience, ExperienceTableId } from "./tables/Experience.sol";
import { ActiveCycle, ActiveCycleTableId } from "./tables/ActiveCycle.sol";
import { CurrentCycle, CurrentCycleTableId } from "./tables/CurrentCycle.sol";
import { PreviousCycle, PreviousCycleTableId } from "./tables/PreviousCycle.sol";
import { CycleTurns, CycleTurnsTableId } from "./tables/CycleTurns.sol";
import { CycleTurnsLastClaimed, CycleTurnsLastClaimedTableId } from "./tables/CycleTurnsLastClaimed.sol";
