// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum StatmodOp {
  ADD,
  MUL,
  BADD
}

enum EleStat {
  NONE,
  PHYSICAL,
  FIRE,
  COLD,
  POISON
}
