// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum EffectRemovabilityId {
  BUFF,
  DEBUFF,
  PERSISTENT
}

enum SkillType {
  COMBAT,
  NONCOMBAT,
  PASSIVE
}

enum TargetType {
  SELF,
  ENEMY,
  ALLY,
  SELF_OR_ALLY
}
