// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IClaimCycleTurnsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClaimCycleTurnsSystem {
  function claimCycleTurnsSystem(bytes memory args) external returns (bytes memory);
}
