// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICycleActivateCombatSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICycleActivateCombatSystem {
  error CycleActivateCombatSystem__InvalidMapPrototype();
  error CycleActivateCombatSystem__BossMapAlreadyCleared();

  function executeTyped(uint256 wandererEntity, uint256 mapEntity) external;

  function execute(bytes memory args) external returns (bytes memory);
}
