// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILearnCycleSkillSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILearnCycleSkillSystem {
  error LearnCycleSkillSystem__SkillNotInGuiseSkills();
  error LearnCycleSkillSystem__LevelIsTooLow();

  function learnFromCycle(bytes memory args) external returns (bytes memory);
}
