// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPermSkillSystem {
  error PermSkillSystem__MustHaveNoActiveCycle();
  error PermSkillSystem__SkillNotLearnedInPreviousCycle(uint256 previousCycleEntity);
  error PermSkillSystem__NotEnoughIdentity();

  function executeTyped(uint256 wandererEntity, uint256 skillEntity) external;

  function execute(bytes memory args) external returns (bytes memory);
}
