// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRandomEquipmentSubSystem {
  function executeTyped(uint32 ilvl, uint256 randomness) external returns (uint256 lootEntity);
}
