// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IWNFTSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWNFTSystem {
  function name() external view returns (string memory);

  function symbol() external view returns (string memory);

  function tokenURI(bytes32 tokenId) external view returns (string memory);
}
